misc dep bumps
Agoric/ui-kit pull request #111
Opened 2024-05-10 18:42 UTC by turadg

no ticket

## Description

Had free hands during SnT

### Security Considerations

### Scaling Considerations

### Documentation Considerations

### Testing Considerations

2024-05-10 19:03 UTC, samsiegart requested changes
Seems like build is failing now, maybe because of yarn version?

2024-05-10 19:03 UTC, samsiegart commented on package.json
> +    "ava": "^6.1.3",
I'd like to try removing ava altogether since we don't have any ava test here anymore afaik

2024-05-10 19:33 UTC, turadg commented
> Seems like build is failing now, maybe because of yarn version?

I think it's the TS bump parsing this differently, or this was bumped
```
../../node_modules/@cosmjs/encoding/build/utf8.d.ts(1,1): error TS1490: File appears to be binary.
```

I'll come back to this in another meeting :)

2024-05-29 04:26 UTC, samsiegart approved these changes
Sorry for delay, I was having trouble testing with `yarn link`. I'm just going to approve because the ui tutorial points to a stable version anyway. When this publishes, I'll validate, publish a new minor version, and update the ui tutorial to use it.

2024-05-29 04:27 UTC, merged